# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWT9i2r7vk96oTXEhvoZUP8CmnD_hP8p
"""

import plotly.express as px
import pandas as pd

# Sample Data
df = px.data.gapminder().query("year == 2007")

# Interactive Scatter Plot
fig = px.scatter(df,
                 x="gdpPercap",
                 y="lifeExp",
                 size="pop",
                 color="continent",
                 hover_name="country",
                 log_x=True,
                 size_max=60,
                 title="GDP vs Life Expectancy (2007)")

fig.show()